CREATE DATABASE IF NOT EXISTS spy CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE spy;

CREATE TABLE IF NOT EXISTS admin (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    last_name VARCHAR(60) NOT NULL,
    first_name VARCHAR(60) NOT NULL,
    email CHAR(100) NOT NULL UNIQUE,
    password CHAR(255) NOT NULL,
    creation_date DATE NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS nationality (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    country VARCHAR(60) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS country (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS agent (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    last_name VARCHAR(60) NOT NULL,
    first_name VARCHAR(60) NOT NULL,
    birth_date DATE NOT NULL,
    code_id CHAR(60) NOT NULL,
    nationality_id INT(11) NOT NULL,
    CONSTRAINT FK_nationality_id FOREIGN KEY (nationality_id) REFERENCES nationality(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS skill (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS agent_skill (
	agent_id INT(11) NOT NULL,
    skill_id INT(11) NOT NULL,
    PRIMARY KEY (agent_id, skill_id),
    CONSTRAINT FK_agent_id FOREIGN KEY (agent_id) REFERENCES agent(id),
    CONSTRAINT FK_skill_id FOREIGN KEY (skill_id) REFERENCES skill(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS mission_status (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    status VARCHAR(60) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS mission_type (
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    type VARCHAR(60) NOT NULL
) ENGINE=InnoDB;
